### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Glidingdiplomat** [Glidingdiplomat/prework-study_guide#6]
# JavaScript

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and rea the information

## Acceptance Criteria 
Given a Prework Study Guide website 
When I view the study guide
THEN I can see the four topics I learned along with a suggestion on whatIi should study first

**Comment by krishanjangid** [comment]
Hello Buddy,
here is an roadmap to ace javascript: https://roadmap.sh/javascript
and read this e-book for better understanding : https://javascript.info

for study guide i think one of the best is roadmap.sh must check it out!
keep do practice daily with consistency.

Happy Learning!
